<?php
namespace frontend\components;

use common\models\Translates;
use Yii;
use yii\base\InvalidConfigException;
use yii\helpers\Html;
use yii\base\Widget;
use yii\data\Pagination;
use yii\helpers\Url;

class MyPaginationFeedbacks  extends \yii\widgets\LinkPager
{

    public $options = ['class' => 'loader_more'];
//
    public $nextPageLabel = '';
    public $prevPageLabel = '';




    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $translates = Translates::getTranslate('feedbacks');
        $this->prevPageLabel = '&nbsp;&#60;&nbsp;&nbsp;'.$translates['pagination_prev'].' &nbsp;';
        $this->nextPageLabel = '&nbsp;'.$translates['pagination_next'].' &nbsp;&#62;';
    }

    protected function renderPageButton($label, $page, $class, $disabled, $active)
    {
        $options = ['class' => $class === '' ? null : $class];
        if ($active) {
            Html::addCssClass($options, $this->activePageCssClass);
        }
        if ($disabled) {
            Html::addCssClass($options, $this->disabledPageCssClass);


            return  Html::tag('span', $label);
        }
        $linkOptions = $this->linkOptions;
        $linkOptions['data-page'] = $page;
        $linkOptions['class'] = 'next';



//        return Html::a($label,$this->pagination->createUrl($page), $linkOptions);



        $page = (int)$page + 1;

        return Html::a($label,'feedbacks?page='.$page, $linkOptions);

    }


    protected function renderPageButtons()
    {
        $pageCount = $this->pagination->getPageCount();
        if ($pageCount < 2 && $this->hideOnSinglePage) {
            return '';
        }

        $buttons = [];
        $currentPage = $this->pagination->getPage();

        // first page
        $firstPageLabel = $this->firstPageLabel === true ? '1' : $this->firstPageLabel;
        if ($firstPageLabel !== false) {
            $buttons[] = $this->renderPageButton($firstPageLabel, 0, $this->firstPageCssClass, $currentPage <= 0, false);
        }

        // prev page
        if ($this->prevPageLabel !== false) {
            if (($page = $currentPage - 1) < 0) {
                $page = 0;
            }
            $buttons[] = $this->renderPageButton($this->prevPageLabel, $page, $this->prevPageCssClass, $currentPage <= 0, false);
        }

        // internal pages
//        list($beginPage, $endPage) = $this->getPageRange();
//        for ($i = $beginPage; $i <= $endPage; ++$i) {
//            $buttons[] = $this->renderPageButton($i + 1, $i, null, false, $i == $currentPage);
//        }

        // next page
        if ($this->nextPageLabel !== false) {
            if (($page = $currentPage + 1) >= $pageCount - 1) {
                $page = $pageCount - 1;
            }
            $buttons[] = $this->renderPageButton($this->nextPageLabel, $page, $this->nextPageCssClass, $currentPage >= $pageCount - 1, false);
        }

        // last page
        $lastPageLabel = $this->lastPageLabel === true ? $pageCount : $this->lastPageLabel;
        if ($lastPageLabel !== false) {
            $buttons[] = $this->renderPageButton($lastPageLabel, $pageCount - 1, $this->lastPageCssClass, $currentPage >= $pageCount - 1, false);
        }

        return Html::tag('div', implode("\n", $buttons), $this->options);
    }
}